name: companion
description: Beautiful and meaningful connection with the WORD
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  stacked_shared: any
  google_generative_ai: ^0.4.0
  logger: ^1.4.0
  path_provider: ^2.1.3
  sqflite: ^2.3.3+1
  sqflite_migration_service: ^2.0.0-nullsafety.1
  share_plus: ^7.2.0
  flutter_tts: ^3.8.4
  audioplayers: ^6.0.0

flutter_launcher_icons:
  image_path_android: "assets/icons/companion-icon.png"
  image_path_ios: "assets/icons/companion-icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/icons/companion-icon.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/icons/companion-icon.png" # only available for Android 8.0 devices and above
  adaptive_icon_monochrome: "assets/icons/companion-icon.png" # only available for Android 13 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#FDFAF3"
  web:
    generate: true
    image_path: "assets/icons/companion-icon.png"
    background_color: "#FDFAF3"
    theme_color: "#FDFAF3"
  windows:
    generate: true
    image_path: "assets/icons/companion-icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/companion-icon.png"

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/data/
    - assets/sql/
    - assets/sound/
  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Outfit-Light.ttf
          weight: 200
        - asset: assets/fonts/Outfit-Thin.ttf
          weight: 300
        - asset: assets/fonts/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Outfit-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Outfit-Black.ttf
          weight: 900
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
